# Generated by Django 5.2.5 on 2025-08-21 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hired_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
