### refresh tokens
POST http://localhost:8000/api/v1/token/refresh/
Content-Type: application/json

{
	"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTc3Mjg0OCwiaWF0IjoxNzU1Njg2NDQ4LCJqdGkiOiIyYzEwZjQxMzgyZWU0ZWVmYTgyNDBkZGU1YzUwYTE0NyIsInVzZXJfaWQiOiI1ZTNiOTA1My0yODBkLTQxMWUtOWY4Ny1jOTA0NWQ3ODNhNzUifQ.s26rgoCYCljn15Vq7fXf7uNXtzYIPg_HkOb1L5h3u2Y"
}

### login as ADMIN to get tokens
POST http://localhost:8000/api/v1/token/
Content-Type: application/json

{
	"email": "akbarjondev007@gmail.com",
	"password": "root1234"
}

### login as TEACHER to get tokens
POST http://localhost:8000/api/v1/token/
Content-Type: application/json

{
	"email": "sam@example.com",
	"password": "newpassword123"
}
