### login to get tokens
POST http://localhost:8000/api/v1/token/
Content-Type: application/json

{
	"email": "akbarjondev007@gmail.com",
	"password": "root1234"
}

### refresh tokens
POST http://localhost:8000/api/v1/token/refresh/
Content-Type: application/json

{
	"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTY5NjI1NywiaWF0IjoxNzU1NjA5ODU3LCJqdGkiOiJjZGFmNmZjNzgwMDA0NzM4YmQyOGNlMWY5YWQxNGFhMSIsInVzZXJfaWQiOiI1ZTNiOTA1My0yODBkLTQxMWUtOWY4Ny1jOTA0NWQ3ODNhNzUifQ.rpwHDz3oYtiEaveUOEOhu9i3OlNvX-Si_NoVPCUZXJA"
}
